# Generated by Django 5.2.6 on 2025-09-09 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_number", models.CharField(max_length=20)),
                ("owner_name", models.CharField(blank=True, max_length=200)),
                ("owner_email", models.EmailField(blank=True, max_length=254)),
                ("status", models.CharField(blank=True, max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "condo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="core.condo",
                    ),
                ),
            ],
            options={
                "ordering": ["condo__name", "unit_number"],
                "unique_together": {("condo", "unit_number")},
            },
        ),
    ]
