# Generated by Django 5.2.6 on 2025-09-18 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_booking_workflow_and_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="condo",
            options={},
        ),
        migrations.AlterModelOptions(
            name="parkingspot",
            options={},
        ),
        migrations.AlterModelOptions(
            name="unit",
            options={},
        ),
        migrations.AlterModelOptions(
            name="unitparkingassignment",
            options={"ordering": ["-start_date"]},
        ),
        migrations.AlterField(
            model_name="condo",
            name="city",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="condo",
            name="code",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="condo",
            name="province",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="parkingspot",
            name="spot_type",
            field=models.CharField(
                choices=[("RESIDENT", "Resident"), ("VISITOR", "Visitor")],
                default="RESIDENT",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="shorttermbooking",
            name="guest_first_name",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="shorttermbooking",
            name="guest_last_name",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="shorttermbooking",
            name="id_country",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="shorttermbooking",
            name="id_number",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="shorttermbooking",
            name="id_province_state",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="shorttermbooking",
            name="id_type",
            field=models.CharField(
                choices=[
                    ("LICENSE", "Driver’s License"),
                    ("PASSPORT", "Passport"),
                    ("OTHER", "Other"),
                ],
                default="LICENSE",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="shorttermbooking",
            name="parking_spot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="core.parkingspot",
            ),
        ),
        migrations.AlterField(
            model_name="shorttermbooking",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="core.unit",
            ),
        ),
        migrations.AlterField(
            model_name="shorttermbooking",
            name="vehicle_plate",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="unit",
            name="status",
            field=models.CharField(
                choices=[
                    ("OWNER_OCCUPIED", "Owner Occupied"),
                    ("TENANT", "Tenant"),
                    ("VACANT", "Vacant"),
                ],
                default="OWNER_OCCUPIED",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="unit_number",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="unitparkingassignment",
            name="parking_spot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="core.parkingspot",
            ),
        ),
    ]
